### ISSUE TITLE
Issues with the footer

### ISSUE THREAD

**Issue by TanAsMat** [TanAsMat/kraken-good-accessibility#1]
Hi Christian, @thatkidmadrid
I am having a trouble with the footer and I am unsure how to solve it. I have tried a couple things, but it is still not happy. I was wondering what am I doing wrong. I sent in what MarkBot is saying and also my code.

![Screen Shot 2021-10-06 at 2 42 14 PM](https://user-images.githubusercontent.com/77473165/136264065-c95aa7b9-62f5-4cc0-856b-b41a175fb04f.png)
![Screen Shot 2021-10-06 at 2 42 23 PM](https://user-images.githubusercontent.com/77473165/136264077-1f986884-fefc-45e5-a293-105b0d494ada.png)

**Comment by thatkidmadrid** [comment]
if we take a look at the first error, it should be clear what the others are complaining about too

let's break it down:
You're definitely on the right track, but Markbot is expecting to see a slightly different structure in the footer.

`footer nav > ul > li:first-child > a[aria-label]`
This means it's expecting to see:
- an `<a>` tag with an attribute called `aria-label` ✅ 
- this `<a aria-label="appropriate label">` should be inside an `<li>` ✅ 
- this `<li>` should be in a `<ul>` ✅ 
- this `<ul>` should be in a `<nav>`
- this `<nav>` should be in a `<footer>`

something like this:
```
<footer>
    <nav>
        <ul>
            <li>
                <a href="#some link" aria-label="appropriate label">...</a>
            </li>
            ...
        <ul>
    </nav>
</footer>
```
looking at your code, you're using a generic `<div>`. Changing this to a more appropriate tag `<nav>` should address the rest of the errors as I see the rest of the stuff looks to be ok.
